### PR TITLE
35-advanced-search-fe-be

### LINKED ISSUE #35: Advanced Search - MVP
#55 
Users should be able to click on a button called "Advanced Search" located next to the "Search" button on the Browse page.
When clicked, it should expand and show the following input boxes:

- Text (this will go against Title, summary and transcript text)
- Keywords
- User that uploaded the transcript
- Mentor (just a text field for now but later we need to ensure the mentor exists or we would add it to the DB)
- Category (pd session vs tech session)
- Syllabus module
- Duration

### PR DESCRIPTION
**Pull request by leilafarsani**
- [x]  ✨ New feature - new behaviour has been implemented
- [ ] 🐛 Bug fix - existing behaviour has been made to behave
- [ ]  ♻️ Refactor - the behaviour has not changed, just the implementation
- [ ] ⚙️ Chore - maintenance task, behaviour and implementation haven't changed

#### Purpose 

This pull request adds the "Advanced Search" feature to the application, allowing users to perform more targeted searches for transcripts. The feature includes the following input fields:

- Keywords: Users can enter specific keywords to search for transcripts that contain those keywords.
     (We should decide what keywords supposed to be)
- User: Users can search for transcripts uploaded by a particular user.
- Leader: Users can enter the name of a leader to filter transcripts associated with that leader.
- Cohort: Users can select between different cohorts to narrow down the search results.
- Syllabus Module: Users can enter the name of a syllabus module to search for transcripts related to that module.
- Duration: Users can specify the desired duration of transcripts to filter the search results.

The implementation ensures that the search is exact and case-insensitive.

This pull request introduces both backend and frontend updates. It's including the API route, necessary pages, database queries to support the "Advanced Search" feature. It also includes the frontend updates including necessary components to display the search results or appropriate messages.

## Testing
- `npx prisma migrate dev --name init`
- `npm run dev`
- login with github 
- Test the "Advanced Search" feature by:
-- Clicking on the "Advanced Search" button.
-- Entering specific search criteria.
-- Verifying the accuracy of the search results.
-- Testing different combinations of search parameters and error handling.

### Author Checklist

- [x]  have written a title that reflects the relevant ticket
- [x] I have written a description that says what the PR does and how to validate it
- [x]  I have linked to the project board ticket (and any related PRs/issues) in the Links section
- [x] I have added a link to this PR to the ticket
- [ ]  I have requested reviewers here and in my team chat channel

### CODE REVIEW

**Comment by susanssky** [comment]
Is this my problem? why can't I search for anything?
Screenshot 2023-07-09 at 21 57 25

**Comment by leilafarsani** [comment]
Hey @susanssky !
are is not supposed to be considered as keyword, as I mentioned in the description we should decide about the keywords , please che the ones that we have our data and models prepared in DB. Thank you very much

**Comment by susanssky** [comment]
????? so what word I can type???

**Comment by susanssky** [comment]
1/Do you think it is better not to combine simple search and advanced search with the dashboard page, but to have separate pages?
2/Could you tell me why to use the third package SWR? there is a `fetch()` to fetch data.....

**Comment by leilafarsani** [comment]
@susanssky Thanks for the review 

1/ Its related to the design and we decided not to focus at design at this stage, I think it is fine to have it here now and will definitely change based on our design and our work flow!
2/SWR simplifies data fetching, caching, and error handling, making it easier and more efficient to work with data.

**Comment by susanssky** [comment]
2/There is fetch() function that can fetch too... I think you need to read Next.js document again

**Review by susanssky — APPROVED** [review]
If there are bugs in the future, please fix them as soon as possible.

**Comment by leilafarsani** [comment]
I saw SWR in the documentation 🤔

**Comment by susanssky** [comment]
IT IS PAGE ROUTER, WE ARE USING APP ROUTER

**Comment by leilafarsani** [comment]
Sorry wrong comment

**Comment by leilafarsani** [comment]
I have a question, does it harm using SWR if working nicely?

**Comment by susanssky** [comment]
Currently, there is no any harm because you used 'use client' to prevent useSWR from causing errors. However, I am planning to refactor and use Server Components in the future.
And I am wondering if, since all files are using 'use client', it might be better to 'go back to using React'...

**Pull request merged**
