### PR TITLE
24 search functionality frontend

### LINKED ISSUE #24: [frontend]Search Transcript
#50  A text box to enter a text to search against the content of transcripts.
It should not allow to search text of less than 3 characters
After pressing enter the application should display the matching records

### PR DESCRIPTION
**Pull request by leilafarsani**
- [x]  ✨ New feature - new behaviour has been implemented
- [ ] 🐛 Bug fix - existing behaviour has been made to behave
- [ ]  ♻️ Refactor - the behaviour has not changed, just the implementation
- [ ] ⚙️ Chore - maintenance task, behaviour and implementation haven't changed

#### Purpose 

- A text box to enter a text to search against the content of transcripts.
- It should not allow to search text of less than 3 characters
- After pressing enter the application should display the matching records

### How to check
- Create the route.ts file in the app/api/search directory and add the following code to handle the search API route. 
```tsx
import { NextRequest, NextResponse } from "next/server"

import { prisma } from "@/lib/prisma"

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url)
  const query = searchParams && searchParams.get("q")
  try {
    if (!query || query.length < 3) {
      throw new Error(
        "Invalid request: Query must be at least three characters long"
      )
    }

    const sentences = await prisma.sentence.findMany({
      where: {
        transcription: {
          sentences: {
            some: {
              content: {
                contains: query,
                mode: "insensitive",
              },
            },
          },
        },
      },
      include: {
        transcription: true,
      },
    })

    await prisma.searchQuery.create({
      data: {
        query,
      },
    })

    return NextResponse.json(sentences)
  } catch (error: any) {
    console.error(error)
    return new Response(error.message, { status: 500 })
  }
}
```
- Enter a search query in the search input field and press Enter.
- Verify that the search query is properly encoded and passed to the search API route.
- Check if the search results are displayed or if the appropriate error message is shown for invalid queries.

### Author Checklist

- [x]  have written a title that reflects the relevant ticket
- [x] I have written a description that says what the PR does and how to validate it
- [x]  I have linked to the project board ticket (and any related PRs/issues) in the Links section
- [x] I have added a link to this PR to the ticket
- [ ]  I have requested reviewers here and in my team chat channel

### CODE REVIEW

**Comment by susanssky** [comment]
Can you please remove the search bar from the login page? Unless you don't mind presenting it in this style during the demonstration, especially the style of displaying search results.

As a trainee user, would they like this type of search results? 
They use the search function to find related posts, cohort names, syllabus names, session names, etc., just like how Google's search input keywords can find webpage titles. If you don't like it, you can keep it unchanged.

**Comment by leilafarsani** [comment]
Thanks @susanssky for your commen. As decided in the meeting with Micheal, we were supposed to keep it as it is for now, until we have our design ready and follow that.
Also, about the search functionality this was the purpose of the related issue to search the transaction based on the search What you mentioned here is related to issue #52  that I am currently working and will make another PR for it.

**Comment by leilafarsani** [comment]
@susanssky I updated this! Thanks!

**Comment by susanssky** [comment]
> @susanssky I updated this! Thanks!

Sorry, you want me to approve for tomorrow's demo? or?

**Comment by leilafarsani** [comment]
No, I want you to approve it if all ok, if not I appreciate for further feedback. Thanks!

**Comment by susanssky** [comment]
> No, I want you to approve it if all ok, if not I appreciate for further feedback. Thanks!

If you don't want to approve for tomorrow demo, so can you wait until to Saturday night? Thanks

**Comment by leilafarsani** [comment]
Yes, sure. No worries!

**Review by susanssky — CHANGES_REQUESTED** [review]
1. Could you create the sub-directory for putting the SearchInput.tsx, Sentences.tsx in the components directory?
2. As a trainee, I hope I can search again when it has searched for something. So I hope you can put the search field on the search result page.
3. Could you add the search button for click to search?

**Comment by leilafarsani** [comment]
@susanssky Thanks for your great comments.
1. done
2.  I will do with another issue
3. related to the design

**Review by susanssky — APPROVED** [review]
If there are bugs in the future, please fix them as soon as possible.

**Comment by leilafarsani** [comment]
sure but what bugs you meant?

**Pull request merged**
