### PR TITLE
37 generate transcript summary

### LINKED ISSUE #37: [fe+be]Generate Transcript Summary
Call OpenAI to generate a summary of the whole text of the transcript. This will be called when the user uploads the transcript and will populate the Summary field during the creation of the Transcript.

Example:
https://platform.openai.com/examples/default-tldr-summary

### PR DESCRIPTION
**Pull request by susanssky**
This is a:

- [x] ✨ **New feature** - new behaviour has been implemented
- [ ] 🐛 **Bug fix** - existing behaviour has been made to behave
- [ ] ♻️ **Refactor** - the behaviour has not changed, just the implementation
- [ ] ⚙️ **Chore** - maintenance task, behaviour and implementation haven't changed

### Description

- **Purpose** - 
Call OpenAI to generate a summary of the whole text of the transcript. This will be called when the user uploads the transcript and will populate the Summary field during the creation of the Transcript.

Example:
https://platform.openai.com/examples/default-tldr-summary

- **How to check** - 
**First, go to OpenAI and create an account to obtain an API Key. (Unfortunately, I cannot provide my API Key as it is not free.)**
1. `npx prisma migrate dev --name init`
2. after login with github
3. go http://localhost:3000/dashboard/create-post
4. fill out cohort,syallbus,session,leader
5. put your openAI API Key
6. upload the srt file
7. click the `generate` button on the summary 
8. click the `submit`

### Links
- Story: #37

### Author checklist

- [X] I have written a title that reflects the relevant ticket
- [X] I have written a description that says what the PR does and how to validate it
- [X] I have linked to the project board ticket (and any related PRs/issues) in the Links section
- [X] I have added a link to this PR to the ticket
- [ ] I have requested reviewers here and in my team chat channel

- [ ] I have explicitly tested the access rights for _at least_ unauthenticated and admin cases

### CODE REVIEW

**Comment by leilafarsani** [comment]
I got this, can you please explain what is that about?
IMAGE 2023-07-11 22:41:14

**Comment by susanssky** [comment]
> I got this, can you please explain what is that about? IMAGE 2023-07-11 22:41:14

Change another one because your openAI account is limit exceeded 
So pay or borrow someone's API key

**Comment by leilafarsani** [comment]
Trying it again, this time it doesn't give me the summary option? I don’t understand why? do you think it might be because I used the same srt file as before ?

**Review by leilafarsani — APPROVED** [review]
Well done @susanssky 

Great job! Just please mention 

`npm install openai`

in the description!

Also, when moving to the transcription page, only the summary will be shown, and transcription itself is empty, if you think it is better to have transcription itself as well maybe? 
I approved this anyway!

**Comment by susanssky** [comment]
> Well done @susanssky
> 
> Great job! Just please mention
> 
> `npm install openai`
> 
> in the description!
> 
> Also, when moving to the transcription page, only the summary will be shown, and transcription itself is empty, if you think it is better to have transcription itself as well maybe? I approved this anyway!

I thought you knew... because you didn't mention npm I for SWR...
? The transcription isn't empty. You need to click the accordion

**Comment by leilafarsani** [comment]
Yes,  right.  it was hiding that time :)))

**Pull request merged**
