### PR TITLE
11-transcripts-metadata

### LINKED ISSUE #11: Transcripts Metadata
We will add Metadata capabilities to our transcripts

### PR DESCRIPTION
**Pull request by susanssky**
This is a:

- [x] ✨ **New feature** - new behaviour has been implemented
- [ ] 🐛 **Bug fix** - existing behaviour has been made to behave
- [ ] ♻️ **Refactor** - the behaviour has not changed, just the implementation
- [ ] ⚙️ **Chore** - maintenance task, behaviour and implementation haven't changed

### Description

- **Purpose** - 
We will add Metadata capabilities to our transcripts
When performing searches of transcripts are we only doing text search or are we also searching by other criteria like keywords, categories, speaker, participantes, duration, etc. This story is to create those capabilities. If we decide add these options in the search, we need to add these in the database, and post create and update.

- **How to check** - 
none...

### Links
- Story: #11

### Author checklist

- [X] I have written a title that reflects the relevant ticket
- [X] I have written a description that says what the PR does and how to validate it
- [X] I have linked to the project board ticket (and any related PRs/issues) in the Links section
- [X] I have added a link to this PR to the ticket
- [ ] I have requested reviewers here and in my team chat channel

- [ ] I have explicitly tested the access rights for _at least_ unauthenticated and admin cases

### CODE REVIEW

**Review by leilafarsani — COMMENTED** [review]
Thanks @susanssky I am happy with this, I am just thinking adding the "duration" field,  just SPECIFICALLY to the Post model ?

**Comment by susanssky** [comment]
@leilafarsani Due to my inability to understand the necessity of the 'duration' field, this application is intended for reading articles, not watching videos

**Comment by leilafarsani** [comment]
@susanssky Yes, I know but by duration meant an estimated reading time! @alfonsocanuk I would like to know your idea as I saw you mentioned "duration" in the description of the issue as well?! 
I personally think it enhances search capabilities.

**Comment by susanssky** [comment]
@leilafarsani how do you count reading time......?

**Comment by leilafarsani** [comment]
As I am aware one way when counting reading time, is we estimate it based on the average reading speed of adults, which is around 200 to 300 words per minute. By dividing the total word count of an article by the average reading speed, we can calculate the estimated reading time in minutes. It's important to note that this is just an approximation as reading speeds can vary among individuals. For example, if an article has 800 words and the average reading speed is 200 words per minute, the estimated reading time would be approximately 4 minutes.
I think in the platforms like Medium,  they use a similar approach to estimate reading time. This helps readers get an idea of how long it might take them to read an article before they begin.

**Comment by susanssky** [comment]
@leilafarsani added

**Review by leilafarsani — APPROVED** [review]

**Pull request merged**
