### PR TITLE
39-update-transcription-fe-be

### LINKED ISSUE #39: Edit transcript details
#69 The user that uploaded the transcript should be able to open a transcript and edit some of the details.

Fields that can be edited from the Transcript information:
- <del>Title</del> **session**
- Summary
- <del>Keywords</del> (It isn't necessary)
- Mentor
- Syllabus module
- <del>Category</del> **cohort**

### PR DESCRIPTION
**Pull request by leilafarsani**
- [x] ✨ **New feature** - new behaviour has been implemented
- [ ] 🐛 **Bug fix** - existing behaviour has been made to behave
- [ ] ♻️ **Refactor** - the behaviour has not changed, just the implementation
- [ ] ⚙️ **Chore** - maintenance task, behaviour and implementation haven't changed

#### Purpose:
This PR introduces a post editing feature to both the frontend and backend. Users can now easily modify their post details, including cohort name, syllabus name, session name, leader name, and summary. The frontend includes an intuitive edit form with input fields for these details, and upon save or canceling for any reason, the backend securely handles API endpoint and data updates with proper validation.

- **Testing** - 

- `npx prisma migrate dev --name init`
- `npm run dev`
-  login with github
- click on any post in the list, click edit button, make some updates and play around with save and cancel buttons.
- You might need to refresh the page to see the result on the table and other related parts in dashboard. 

### Author Checklist

- [x]  have written a title that reflects the relevant ticket
- [x] I have written a description that says what the PR does and how to validate it
- [x]  I have linked to the project board ticket (and any related PRs/issues) in the Links section
- [x] I have added a link to this PR to the ticket
- [x]  I have requested reviewers here and in my team chat channel

### CODE REVIEW

**Comment by susanssky** [comment]
Would you be willing to spend a few extra days researching how to edit the transcription?

**Comment by leilafarsani** [comment]
Hi Susan,

What do you mean exactly ?
I did based on the requirements of the issue!
Can you please explain more? Thanks

**Comment by leilafarsani** [comment]
@maxf  Can you please review this PR! Many Thanks

**Comment by susanssky** [comment]
I thought you would add `edit transcription`

**Comment by leilafarsani** [comment]
Why did you think so?
The issue details was in the board for a while and it was edited version as well. I just did the task related to that exactly...
I was not supposed to edit the issue though 🤔

**Review by susanssky — APPROVED** [review]
The platform for saving subtitles unfortunately doesn't have the capability to edit/update subtitles

**Comment by leilafarsani** [comment]
Thank you for approving this!
I know what you mean. It wasn't included in this issue.So I thought that was not needed.

**Pull request merged**
