### PR TITLE
40-homepage-displayed-transcription-fe-be

### LINKED ISSUE #40: show top 3 viewed, liked, most recently added on Home page
#71 Using statistics and votes collected for Transcripts, show most viewed and most liked transcripts.

What will be displayed:

- Welcome message
- A box showing the top 3 most viewed transcripts
- A box showing the top 3 most liked transcripts
- A box showing the most recently added transcripts
- <del>A box showing recommended transcripts</del> **It is too similar to the second and third ones.** 
- <del>A box showing top categories</del> **There are no categories.**

### PR DESCRIPTION
**Pull request by leilafarsani**
This is a:

- [x] ✨ **New feature** - new behaviour has been implemented
- [ ] 🐛 **Bug fix** - existing behaviour has been made to behave
- [ ] ♻️ **Refactor** - the behaviour has not changed, just the implementation
- [ ] ⚙️ **Chore** - maintenance task, behaviour and implementation haven't changed

### Description

This PR  includes:

Backend API endpoints,  fetching the required data. Components were created on the frontend to display the information. Tested for accuracy and functionality.

#### Purpose

- Welcome message on the homepage.
- Top 3 most viewed transcripts.
- Top 3 most voted transcripts.
- Most 3 recently added transcripts.

#### Checking

- `npx prisma migrate dev --name init`
- `npm run dev`
-  login with Github
-  visit the home which is added to the navbar, and play with new features and check different details.

#### Author Checklist
- [X] I have written a title that reflects the relevant ticket
- [X] I have written a description that says what the PR does and how to validate it
- [X] I have linked to the project board ticket (and any related PRs/issues) in the Links section
- [X] I have added a link to this PR to the ticket
- [X] I have requested reviewers here and in my team chat channel

### CODE REVIEW

**Comment by susanssky** [comment]
all transcriptions should change "posts" because the "posts" collective all data, so we should use posts

**Comment by leilafarsani** [comment]
Yes, they store in the the Post, However there is relation between transcription model and post model,which allows using transcription where relate them with post and this is what I tried to do here.
The task is more specific to transcription so I preferred the focus on transcription but definitely while making sure applying it's relation with Post. This is why it works fine as It ables to get the stored data from the Post and also store new data in the post again. like when number of views increments with each new visit.

**Comment by susanssky** [comment]
I really can't understand why it is necessary to extract data in the child data and not in the parent data?

**Comment by leilafarsani** [comment]
Is there anything wrong with it?
I explained it was more because of more clarification based on the task

**Comment by susanssky** [comment]
Just because you explained something doesn't mean you wrote it correctly. The question asks for the
Top 3 most viewed
Top 3 most voted
Most 3 recently added, and it is clear that you cannot obtain this information from the transcription model alone. Therefore, why would you still try to obtain it from the transcription model?

**Pull request merged**
